config/routes.rb
Rails.application.routes.draw do  
    root 'pages#index'

    # (Static) pages
    get 'contact', to: 'pages#contact', as: :contact
    get 'merkur', to: 'pages#merkur', as: :merkur

    # Create a new customer case
    post 'case', to: 'pages#customer_case', as: :customer_case

    # Projects
    get 'projects', to: 'projects#index', as: :projects
    get 'projects/view/:id/(:title)', to: 'projects#view', as: :project

    # Manager 
    namespace :manager do
        root 'projects#index'        
        resource :projects   

        # Manage customer cases
        get 'cases', to: 'cases#index', as: :cases     
        resource :cases, only: :delete
    end
end

app/models/customer_case.rb
# == Schema Information
#
# Table name: customer_cases
#
#  id            :integer          not null, primary key
#  name          :string(255)      not null
#  email_address :string(255)      not null
#  message       :text             not null
#  created_at    :datetime
#  updated_at    :datetime
#

class CustomerCase < ActiveRecord::Base
    default_scope { order(created_at: :desc) }

    # Validation rules
    validates :name, presence: { message: "Jag uppfattade inte namnet. Vad ska jag kalla dig?" }
    validates :email_address, presence: { message: "Hur ska jag återkomma till dig? Vänligen ange en giltig mailadress." }
    validates :message, presence: { message: "Ingen text hittades i meddelandet." }, length: { minimum: 10, maximum: 500, message: "Vänligen beskriv ditt ärende så detaljerat som möjligt." }
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                :integer          not null, primary key
#  title             :string(255)
#  url_title         :string(255)
#  short_description :string(255)
#  long_description  :text
#  created_at        :datetime
#  updated_at        :datetime
#

class Project < ActiveRecord::Base
    has_many :project_pictures, dependent: :destroy
    default_scope { order(created_at: :desc) }
end

app/models/project_picture.rb
# == Schema Information
#
# Table name: project_pictures
#
#  id                  :integer          not null, primary key
#  project_id          :integer          not null
#  created_at          :datetime
#  updated_at          :datetime
#  avatar_file_name    :string(255)
#  avatar_content_type :string(255)
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#  is_primary          :boolean          default(FALSE)
#

class ProjectPicture < ActiveRecord::Base
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/manager/cases_controller.rb
class Manager::CasesController < ApplicationController
  def index
     @cases = CustomerCase.all
  end
end

app/controllers/manager/projects_controller.rb
class Manager::ProjectsController < ApplicationController
  before_action :set_manager_project, only: [:edit, :update, :destroy]

  # GET /manager/projects
  def index
    @projects = Project.all
    @cases = CustomerCase.all 
  end

  # GET /manager/projects/new
  def new
    @project = Project.new
  end

  # GET /manager/projects/1/edit
  def edit
  end

  # POST /manager/projects
  def create
    @project = Project.new(manager_project_params)

    upload_attached_images

    if @project.save
      redirect_to manager_root_path, notice: "#{@project.title} was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /manager/projects/1
  def update
    if @project.update(manager_project_params)
      upload_attached_images
      redirect_to manager_root_path, notice: "#{@project.title} was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /manager/projects/1
  def destroy
    @project.destroy
    redirect_to manager_root_path, notice: "#{@project.title} was successfully deleted."
  end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_manager_project
      @project = Project.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def manager_project_params
      params[:project].permit(:title, :url_title, :short_description, :long_description)
    end

    def upload_attached_images
      if params[:images] and @project
        params[:images].each { |image|
          @project.project_pictures.create(avatar: image)
        }
      end

      # Make images for a project primary if checked
      if params[:primary_images] and @project
        params[:primary_images].each { |image_id|
          @picture = ProjectPicture.find(image_id) rescue nil
          @picture.update(is_primary: true) unless @picture.nil?
        }
      end
      # Delete images if any selected
      if params[:deleted_images] and @project 
        params[:deleted_images].each { |image_id|
          @picture = ProjectPicture.find(image_id) rescue nil
          @picture.destroy unless @picture.nil?
        }
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def merkur
  end

  def contact
    # Create new customer case to be sent
    @case = CustomerCase.new
  end

  # POST new contact form (creates a case)
  def customer_case
    @case = CustomerCase.new(case_params)

    if @case.save      
      redirect_to root_url,
      notice:  "Tack för att du tog kontakt. Jag återkommer till dig så fort jag kan."
    else      
      render 'contact', 
      notice: "Sorry! Jag förstod inte riktigt vad du ville skriva eller så har du missat någon obligatorisk uppgift."
    end
  end

private
  def case_params
    params[:case].permit(:name, :message, :email_address)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def view
    begin
        if params[:id] or params[:title]
            @project = Project.find_by(url_title: params[:title])
        else
            raise 'No id or title given'
        end
    rescue         
        redirect_to projects_url,
        notice: "Projektet du sökte efter kunde inte hittas."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/manager/cases_helper.rb
module Manager::CasesHelper
end

app/helpers/manager/projects_helper.rb
module Manager::ProjectsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

    # Rernder a thumbnail for project if any
    def project_has_thumbnails? project
        project.project_pictures.size > 2
    end

    def get_primary_pictures project 
        if project and project_has_thumbnails? project
            project.project_pictures.select { |p| p.is_primary == true  }.take(2)
        else
            nil
        end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="sv">
<head>
<%= yield(:meta_tags) %>
<!-- Favicon/touch icons -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="author" content="metsson">
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
<!-- Apple -->
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-touch-startup-image" href="/apple-startup.png">
<!-- Touch icons -->
<link rel="apple-touch-icon" href="/touch-icon-iphone.png">
<link rel="apple-touch-icon" sizes="76x76" href="/touch-icon-ipad.png">
<link rel="apple-touch-icon" sizes="120x120" href="/touch-icon-iphone-retina.png">
<link rel="apple-touch-icon" sizes="152x152" href="/touch-icon-ipad-retina.png">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
<!-- CDNs -->
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<link rel="stylesheet" href="//blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
<%= stylesheet_link_tag    'application', media: 'all' %>
<%= csrf_meta_tags %>
</head>
<body <%= yield(:body_id) %> class="animated fadeIn">
<% if flash[:notice] %>
<div id="flash">
    <p>
        <%= flash[:notice] %>
    </p>
</div>
<% end %>
<!-- Navigation -->
<nav class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= active_link_to root_path, class: 'navbar-brand' do %>
                Metsson
            <% end %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <%= link_to root_path, class: 'dropdown-toggle', "data-toggle" => 'dropdown', "aria-expanded" => 'false', "role" => 'button' do %>
                        Om <span class="caret"></span>
                    <% end %>
                    <ul class="dropdown-menu" role="menu">
                        <li>
                            <%= active_link_to 'Kontakt', contact_path, wrap_tag: :li %>
                        </li>                        
                        <li class="divider"></li>
                        <li>
                            <%= active_link_to 'Om Merkur', merkur_path, wrap_tag: :li %>
                        </li>
                    </ul>
                <li>
                    <%= active_link_to 'Projekt', projects_path, wrap_tag: :li %>
                </li>
                <li>
                    <%= active_link_to 'Kontakt', contact_path, wrap_tag: :li %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>
<%= yield %>
<%= javascript_include_tag 'application' %>
<script src="//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50400145-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/manager/cases/index.html.erb
<div class="container">
    <div class="well">
        <%= link_to manager_root_path, class: 'btn btn-default btn-xs' do %>
            <i class="fa fa-chevron-left"></i> Manage projects
        <% end %>
    </div>
    <h1>
        Customer cases
    </h1>    
    <table class="table table-striped table-hover col-lg-12">
        <thead>
            <tr>
              <th>From</th>              
              <th>Email</th>
              <th>Message</th>
              <th>Time</th>
              <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        <% @cases.each do |customer| %>
            <tr>
                <td>
                    <%= customer.name %>
                </td>
                <td>
                    <%= customer.email_address %>
                </td>
                <td>
                    <%= customer.message.truncate(20) %>   
                </td>
                <td>
                    <%= time_ago_in_words(customer.created_at) %> ago
                </td>
                <td class="btn-group">
                    <%= link_to manager_cases_path, class: 'btn btn-danger btn-sm' do %>
                    <i class="fa fa-remove"></i>
                    <% end %>
                    <%= link_to manager_cases_path, class: 'btn btn-default btn-sm' do %>
                    <i class="fa fa-chevron-right"></i> Read
                    <% end %>                    
                </td>
            </tr>
        <% end %>
        </tbody>
    </table>    
</div>

app/views/manager/projects/_form.html.erb
<%= form_for @project, url: manager_projects_path(id: @project.id), html: { multipart: true }, class: 'form-horizontal' do |f| %>
  <div class="form-group">
    <%= f.label 'Title', class: 'col-lg-2 control-label' %>
    <div class="col-lg-10">
      <%= f.text_field :title, class: 'form-control', placeholder: 'Project title' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'URL-friendly title', class: 'col-lg-2 control-label' %>
    <div class="col-lg-10">
      <%= f.text_field :url_title, class: 'form-control', placeholder: 'Enter URL-friendly' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Short descrption', class: 'col-lg-2 control-label' %>
    <div class="col-lg-10">
      <%= f.text_area :short_description, rows: '4', class: 'form-control', placeholder: 'Describe the project within 250 characters' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Long descrption', class: 'col-lg-2 control-label' %>
    <div class="col-lg-10">
      <%= f.text_area :long_description, rows: '15', class: 'form-control', placeholder: 'Describe the project in details' %>
    </div>
  </div>  
  <div class="form-group">
    <% if @project.project_pictures.size > 0 %>
      <p>Edit pictures</p>      
      <% @project.project_pictures.each  do |image| %>
      <div class="row">
          <div class="col-md-3">
            <%= image_tag image.avatar.url(:thumb) %>
          </div>
          <div class="col-md-4">
            <div class="checkbox">            
              <%= f.label 'Delete', for: image.id, class: 'col-lg-2 control-label' do %>            
              <%= check_box_tag 'deleted_images[]', image.id  %> Delete             
              <% end %>
            </div>
          </div>
          <div class="col-md-5">
            <div class="checkbox">
              <%= f.label 'Make primary', class: 'col-lg-2 control-label' do %>
              <%= check_box_tag 'primary_images[]', image.id  %> Make primary
              <% end %>            
            </div>
          </div>
      </div>
      <hr>
      <% end %>
    <% end %>
  </div>  
  <div class="form-group">
    <%= f.label 'Add pictures', class: 'col-lg-2 control-label' %>
    <div class="col-lg-10">
      <%= file_field_tag "images[]", type: :file, multiple: true %>
    </div>
  </div>  
  <div class="form-group">
    <div class="col-lg-10 col-lg-offset-2">
      <%= link_to 'Cancel', manager_root_path, class: 'btn btn-danger' %>
      <%= f.submit :Save, class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/manager/projects/edit.html.erb
<div class="container">
<h1>
    <i class="fa fa-pencil text-danger"></i>
    Editing "<%= @project.title %>"
</h1>

<%= render 'form' %>
</div>

app/views/manager/projects/index.html.erb
<% content_for :meta_tags do %>
<title>Manage projects</title>
<% end %>

<div class="container">
    <% if @cases %>
        There are <strong><%= @cases.size %></strong> unread case(s).
        <%= link_to "Go to cases", manager_cases_path, class: 'btn btn-success' %>
    <% end %>
    <% if !@projects or @projects.size == 0 %>
    <h1 class="text-center">
        There are no projects in here. Why don't you add one?
        <%= link_to new_manager_projects_path, class: 'btn btn-success btn-sm' do %>
            <i class="fa fa-plus"></i> Create
        <% end %>        
    </h1>
    <% else %>
    <h1>
        Listing all projects <small><%= @projects.size %> project(s) found</small>
        <%= link_to new_manager_projects_path, class: 'btn btn-success btn-sm' do %>
            <i class="fa fa-plus"></i> Create
        <% end %>        
    </h1>
    <table class="table table-striped table-hover col-lg-12">
        <thead>
            <tr>
              <th>ID</th>              
              <th>Title</th>
              <th>Created</th>
              <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        <% @projects.each do |project| %>
            <tr>
                <td>#<%= project.id %></td>                
                <td><%= project.title %></td>
                <td><%= time_ago_in_words(project.created_at) %> ago</td>
                <td>
                    <div class="btn-group">
                    <%= link_to project_path(id: project, title: project.url_title), target: '_blank', class: 'btn btn-default btn-sm' do %>
                    <i class="fa fa-eye"></i> Preview
                    <% end %>
                    <%= link_to manager_projects_path(id: project.id), class: 'btn btn-danger btn-sm', data: { confirm: "Do you really want to delete the project '#{project.title}'" }, method: :delete do %>
                    <i class="fa fa-remove"></i> Delete
                    <% end %>
                    <%= link_to edit_manager_projects_path(id: project.id), class: 'btn btn-primary btn-sm' do %>
                    <i class="fa fa-pencil"></i> Edit
                    <% end %>
                    </div>
                </td>
            </tr>
        <% end %>
        </tbody>
    </table>
    <% end %>
</div>

app/views/manager/projects/new.html.erb
<h1>New manager_project</h1>

<%= render 'form' %>

app/views/pages/_waiting_time.html.erb
  <!-- Action -->
  <div class="well take-action-box animated fadeIn">
      <p class="text-center">
        <%= image_tag('circle-icons/full-color/clock.png', class: 'img-responsive') %>
      </p>
      <p>      
      Just nu är det cirka <strong>45</strong> dagars väntetid för nya projekt.
      <% if show_button %>
      <%= link_to 'Kontakta mig', contact_path, class: 'btn btn-success btn-sm' %>
      <% end %>
      </p>
  </div><!-- Action -->    

app/views/pages/contact.html.erb
<% content_for :meta_tags do %>
<title>Kontakta mig när det gäller webbutveckling</title>
<% end %>

    <div class="jumbotron landing-splash contact">
      <div class="container">
        <h1 class="animated bounceInDown">Jag älskar webbsnack!</h1>
        <p class="animated bounceInRight">
            Det spelar ingen roll vem du är. Inte heller vad du söker.
            Skriver du till mig om webben så är jag idel öra!
        </p>
      </div>
    </div>

<div class="container">
  <%= render 'waiting_time', show_button: false %>
  <% if @case.errors.any? %>
  <div class="alert alert-danger">
    <h3>
      <i class="fa fa-warning"></i> Vänta lite... 
    </h3>
    <p>
      Jag förstod inte riktigt allt du ville ha sagt. Följande fel måste rättas innan du skickar kontaktformuläret igen.
    </p>
    <ul>
    <% @case.errors.messages.values.each do |error| %>
      <% error.each do |message| %>
        <li><%= message %></li>
      <% end %>
    <% end %>
    </ul>
  </div>
  <% end %>
  <%= form_for :case, url: customer_case_path(id: @case.id), html: { multipart: true } do |f| %>
    <div class="form-group">
      <%= f.label 'Namn', class: 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Vem är du?', data: { "validation" => "length", "validation-length" => "min2", "validation-error-msg" => "Vad heter du?"} %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label 'Mailadress', class: 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= f.email_field :email_address, class: 'form-control', placeholder: 'Din mailadress' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label 'Ärende', class: 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= f.text_area :message, rows: '10', class: 'form-control', placeholder: 'Berätta vad du vill veta eller ha hjälp med...', data: { "validation" => "length", "validation-length" => "min30", "validation-error-msg" => "Beskriv ditt ärende detaljerat."} %>
      </div>
    </div>   
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
          <%= button_tag type: :submit, class: 'btn btn-success contact-form-button' do %> 
              <i class="fa fa-envelope"></i> Skicka
          <% end %>
      </div>
    </div>
  <% end %> 
</div>

app/views/pages/index.html.erb
<% content_for :meta_tags do %>
<title>Webbutvecklingsbyrån med det lilla extra</title>
<% end %>
    <div class="jumbotron landing-splash home">
      <div class="container">
        <h1 class="animated bounceInDown">Din webbdröm. Mitt uppdrag.</h1>
        <p class="animated bounceInRight">
            Hej! Mitt namn är <%= link_to 'Merkur', merkur_path %>. En webbentreprenör med djupa kunskaper inom webbutveckling. Oavsett hur stort, galet eller litet ditt webbprojekt är, så har du hamnat på rätt ställe.
        </p>
        <p class="landing-splash-buttons animated bounceInLeft">
                <%= link_to 'Kontakta mig', contact_path, class: 'btn btn-primary btn-lg' %>
                <em class="small">eller</em>
                <%= link_to 'Låt dig inspireras', projects_path, class: 'btn btn-default' %>        
        </p>
      </div>
    </div>
<div class="container">        
    <!-- Quick services' info -->
    <div class="row quick-about-services">
        <div class="col-md-4 col-sm-12">
            <div class="quick-about-services-icon">
                <%= image_tag('circle-icons/full-color/dev.png', class: 'img-responsive') %>
            </div>
            <h2>
                Webbutveckling i världsklass
            </h2>
            <p>
                Med Metsson kan du bara luta dig tillbaka och veta att enbart <strong>webbstandard</strong> samt <strong>professionella</strong> lösningar gäller.
            </p>
        </div>
        <div class="col-md-4 col-sm-12">
            <div class="quick-about-services-icon">
                <%= image_tag('circle-icons/full-color/rocket.png', class: 'img-responsive') %>
            </div>            
            <h2>
                Webbhotell ingår
            </h2>
            <p>
                Igenom din nya webbapplikation får du även webbhotell där säkerhet och supersnabba svarstider är en självklarhet. Helt <strong>kostnadsfritt</strong> första året!

            </p>
        </div>
        <div class="col-md-4 col-sm-12">
            <div class="quick-about-services-icon">
                <%= image_tag('circle-icons/full-color/lightbulb.png', class: 'img-responsive') %>
            </div>            
            <h2>
                Erfaret affärssinne
            </h2>
            <p>
                Oavsett om du är ny på webben eller inte så får du alltid tips av mig om olika <strong>affärsmodeller</strong>
                för din nya webbidé.
            </p>
        </div>           
    </div><!-- Quick services' info -->
    <%= render 'waiting_time', show_button: true %>
</div><!-- container -->

app/views/projects/index.html.erb
<% content_for :body_id do %>
id="portfolio"
<% end %>

<% content_for :meta_tags do %>
<title>Mina senaste projekt</title>
<% end %>

<div class="container" id="showcase">
    <div class="row header">
        <div class="col-md-12">
            <h1 class="animated bounceInDown">
                Några webbprojekt
            </h1>
            <p class="animated bounceInUp">
                <%= link_to 'Här', projects_path %> listar jag ett axplock av mina 
                applikationer. Målet är att dels få dig att förstå hur mycket innovativt tänk som finns att tillgå ifrån min sida, dels försäkra dig om att möjligheterna är obegränsade genom att kombinera <strong>min kompetens</strong> med <strong>din webbidé</strong>.
            </p>
        </div>
    </div>
    <div class="row">
        <% @projects.each do |project| %>    
        <div class="col-md-12">
            <div class="project">
                <h3>
                    <%= project.title %>
                </h3>
                <div class="screen">
                    <% if project_has_thumbnails? project %>
                        <% get_primary_pictures(project).each do |picture| %>
                            <%= link_to project_path(id: project.id, title: project.url_title) do %>
                                <%= image_tag picture.avatar.url(:medium), class: "img-responsive" %>
                            <% end %>            
                        <% end %>
                    <% end %>
                </div>
                <p class="description">
                <%= truncate(project.short_description, length: 200) { link_to " Läs mer", project_path(id: project, title: project.url_title)} %>
                </p>
                <div class="divider"></div>
                <div class="visit">
                    <%= link_to project_path(id: project.id, title: project.url_title), class: 'button' do %>
                        <i class="fa fa-chevron-right"></i>
                        Till projekt
                    <% end %>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/projects/view.html.erb
<%= content_for :meta_tags do %>
<title><%= @project.title %></title>
<% end %>

<div class="container">
    <%= link_to projects_path do %>
        <span class="button back-to-projects"> 
        <i class="fa fa-angle-double-left"></i> Se fler projekt
        </span>
    <% end %> 
    <div class="row">   
        <div class="col-md-7">
            <div class="project-header">
                <h1>
                    <%= @project.title %>
                </h1>
                <section>
                    <p class="lead">
                        <%= @project.short_description %>
                    </p>
                    <% if project_has_thumbnails? @project %>
                        <%= image_tag(get_primary_pictures(@project).first.avatar.url(:medium), class: "img-responsive project-big-picture") %>
                    <% end %>
                </section>
            </div>
            <article>
                <%= raw @project.long_description %>
                <% if project_has_thumbnails? @project %>
                <%= image_tag(get_primary_pictures(@project).second.avatar.url(:medium), class: "img-responsive project-big-picture") %>
                <% end %>            
            </article> 
        </div>
        <!-- Sidebar -->
        <div class="col-md-5">
            <!-- Project pics -->
            <% if @project.project_pictures.size > 0 %>
            <div id="links" class="project-picture-gallery">
                <ul class="list-inline text-center">                       
                    <% @project.project_pictures.take(10).each do |picture| %>
                    <li class="animated shake">
                    <%= link_to picture.avatar.url(:original), "data-gallery" => "" do %>
                        <%= image_tag picture.avatar.url(:thumb), class: "img-responsive" %>
                    <% end %>
                    </li>
                    <% end %>
                </ul>
            </div>            
            <% end %><!-- Project pics -->   
            <aside>
                <div class="well">          
                <h2>Låter detta kul?</h2>
                <p> 
                    Om du har något liknande på gång eller vill veta mer om projektet, tveka inte att <%= link_to 'höra av dig', contact_path %>!
                </p>
                <p>
                <%= link_to projects_path do %>
                    <span class="btn btn-default btn-xs"> 
                    <i class="fa fa-angle-double-left"></i> Se fler projekt
                    </span>
                <% end %> <em>eller</em>
                <%= link_to contact_path do %>
                    <span class="btn btn-success btn-xs"> 
                    <i class="fa fa-envelope"></i> Kontakta mig!
                    </span>
                <% end %>
                </p>
                </div>        
            </aside>                          
        </div>
        <!-- Sidebar -->
    </div>
</div>

<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
    <div class="slides"></div>
    <h3 class="title">Visar bilder för '<%= @project.title %>'</h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>